<a href="https://colab.research.google.com/github/misalsachin/deep_learning-RNN/blob/master/Fake_News_Classifier_Bidirectional_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fake News Classifier Using Bidirectional LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#
teps:

1 import all requred libraries

2 do feature engineering

3 do text preprocessing using NLTK remove stopwords,steming,lower case

2 set vocabulry size & do one_hot representation

4 fix the sentance length &do the padding-pre or post for equal size of sentence length

6 set feature dimension & create sequntial model & add embedding layer & give parameter vocabullry size,dimension,sentence length( Word Embedding)

7 create a Bidirectional LSTM model with 100 neuron 

8 convert dataframe to numpy array

9 do the train test split

10 fit the model with 10 epoch 

11 predict the result & check the accuracy




In [ ]:
import pandas as pd
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Bidirectional
from tensorflow.keras.layers import Dense,Dropout

In [ ]:
df=pd.read_csv('/content/drive/My Drive/LSTM Kaggle fake news dataset/train.csv',engine='python', error_bad_lines=False)

Skipping line 12520: unexpected end of data


In [ ]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
# Check Nan Value in title colum
df['title'].isnull().sum()

339

In [ ]:
# Check Nan Value in whole train dataset
df.isnull().sum()

id           0
title      339
author    1157
text        27
label        0
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
# Deleted Nan/Null values from dataset
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(11022, 4)

In [ ]:
y.shape

(11022,)

In [ ]:
### fix the Vocabulary size
voc_size=5000

In [ ]:
messages=X.copy()

In [ ]:
messages.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages.head()

index  ...                                               text
0      0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1      1  ...  Ever get the feeling your life circles the rou...
2      2  ...  Why the Truth Might Get You Fired October 29, ...
3      3  ...  Videos 15 Civilians Killed In Single US Airstr...
4      4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 5 columns]

In [ ]:
# Data preprocessing
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
#dataset preprocesssing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i]) # remove all other than alphabet & add spece
    review = review.lower()    # convert the dataset in lower case
    review = review.split()    # split the word by space  
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[666, 4928, 1935, 2236, 629, 4512, 325, 4338, 1918, 3128],
 [452, 2127, 2031, 610, 1231, 4029, 1885],
 [83, 7, 3902, 2747],
 [2766, 3239, 1902, 523, 4464, 1218],
 [557, 1231, 3158, 1187, 4648, 1589, 1231, 386, 2582, 2489],
 [518,
  4496,
  4455,
  2460,
  3888,
  4960,
  1036,
  4189,
  4313,
  652,
  3521,
  887,
  1577,
  3004,
  1885],
 [2739, 4313, 2944, 3688, 3137, 3759, 3598, 2968, 3328, 1373, 1131],
 [3946, 631, 1006, 3033, 3714, 3125, 4960, 2693, 3328, 1373, 1131],
 [2530, 2443, 1064, 3521, 2624, 1381, 641, 642, 4960, 2578],
 [2485, 2785, 1436, 1598, 2490, 3163, 23, 555],
 [2998, 3700, 141, 1296, 3402, 1045, 3105, 3763, 660, 2371, 1135],
 [523, 2504, 629, 1381, 4960, 3714],
 [4799, 1761, 3915, 1506, 4672, 3450, 4132, 455, 1039],
 [4585, 4895, 3122, 351, 1892, 4881, 4265, 3328, 1373, 1131],
 [510, 3619, 2698, 1663, 2594, 3328, 1373, 1131],
 [1622, 69, 483, 1891, 1310, 2213, 2318, 3164, 2209, 4192],
 [3546, 717, 2127],
 [167, 2103, 1953, 2770, 4960, 2061, 3797, 1885],
 [2924, 20

In [ ]:
# Embedding Representation -paddin for making same length of sentance
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4338 1918 3128]
 [   0    0    0 ... 1231 4029 1885]
 [   0    0    0 ...    7 3902 2747]
 ...
 [   0    0    0 ...    3 4254 2871]
 [   0    0    0 ... 1992  777 1885]
 [   0    0    0 ...  760  928  490]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  666,
       4928, 1935, 2236,  629, 4512,  325, 4338, 1918, 3128], dtype=int32)

In [ ]:
embedded_docs.astype

<function ndarray.astype>

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               112800    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(11022, (11022,))

In [ ]:
# converting to numpy array
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.astype

<function ndarray.astype>

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_final,y_final,test_size=0.33,random_state=42)

In [ ]:
# model Traning
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=60)

Epoch 1/10
124/124 [==============================] - 6s 47ms/step - loss: 0.3448 - accuracy: 0.8298 - val_loss: 0.2255 - val_accuracy: 0.9082
Epoch 2/10
124/124 [==============================] - 5s 41ms/step - loss: 0.1396 - accuracy: 0.9487 - val_loss: 0.2103 - val_accuracy: 0.9129
Epoch 3/10
124/124 [==============================] - 5s 41ms/step - loss: 0.0845 - accuracy: 0.9726 - val_loss: 0.2491 - val_accuracy: 0.9041
Epoch 4/10
124/124 [==============================] - 5s 41ms/step - loss: 0.0499 - accuracy: 0.9844 - val_loss: 0.2773 - val_accuracy: 0.9090
Epoch 5/10
124/124 [==============================] - 5s 41ms/step - loss: 0.0311 - accuracy: 0.9908 - val_loss: 0.3514 - val_accuracy: 0.9060
Epoch 6/10
124/124 [==============================] - 5s 41ms/step - loss: 0.0242 - accuracy: 0.9919 - val_loss: 0.3850 - val_accuracy: 0.9071
Epoch 7/10
124/124 [==============================] - 5s 41ms/step - loss: 0.0154 - accuracy: 0.9958 - val_loss: 0.4926 - val_accuracy: 0.9090

In [ ]:
# Performance Metrics And Accuracy¶
y_pred=model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1888,  190],
       [ 173, 1387]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.90021990104453

In [ ]:
np.argmax(model.predict(X_test), axis=-1)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
z=(model.predict(X_test) > 0.5).astype("int32")

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.91      0.91      2078
           1       0.88      0.89      0.88      1560

    accuracy                           0.90      3638
   macro avg       0.90      0.90      0.90      3638
weighted avg       0.90      0.90      0.90      3638

