<a href="https://colab.research.google.com/github/misalsachin/deep_learning-RNN/blob/master/Word_Embedding__Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Word  Embedding Techniques using Embedding Layer in Keras **

**Steps**:

1 import all requred libraries

2 set vocabulry size

3 do one_hot representation 

4 fix the sentance length 

5 do the padding-pre or post for equal size of sentence length

*   List item
*   List item



6 set feature dimension

7 create sequntial model & add embedding layer & give parameter vocabullry size,dimension,sentence length

8 comple model with adam optimizer 

9 use the model to predict the word embedding

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
##Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
# Set vacabullary size
voc_size=10000

In [ ]:
# One Hot Representation of given sentence
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[7111, 4645, 1327, 8399], [7111, 4645, 1327, 7793], [7111, 9871, 1327, 1692], [7902, 2187, 4891, 2718, 8284], [7902, 2187, 4891, 2718, 3090], [4244, 7111, 4029, 1327, 1061], [8905, 3684, 5303, 2718]]


In [ ]:
sent_len=8
embedded_docs=pad_sequences(onehot_repr,maxlen= sent_len,padding= 'pre')
print(embedded_docs)

[[   0    0    0    0 7111 4645 1327 8399]
 [   0    0    0    0 7111 4645 1327 7793]
 [   0    0    0    0 7111 9871 1327 1692]
 [   0    0    0 7902 2187 4891 2718 8284]
 [   0    0    0 7902 2187 4891 2718 3090]
 [   0    0    0 4244 7111 4029 1327 1061]
 [   0    0    0    0 8905 3684 5303 2718]]


In [ ]:
# Set Dimension 
dim=10

In [ ]:
model=Sequential()

In [ ]:
 model.add(Embedding(voc_size,10,input_length=sent_len))
 model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175
    0.03367909  0.01944667  0.01066551  0.04450018  0.00096234]
  [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175
    0.03367909  0.01944667  0.01066551  0.04450018  0.00096234]
  [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175
    0.03367909  0.01944667  0.01066551  0.04450018  0.00096234]
  [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175
    0.03367909  0.01944667  0.01066551  0.04450018  0.00096234]
  [-0.01431137  0.01765312  0.02915944 -0.0352341   0.01711595
   -0.02865772  0.03914508 -0.04042567 -0.02964351  0.01348101]
  [ 0.01483481 -0.02012639 -0.02603496  0.00021013  0.04989537
   -0.00745595 -0.04137442 -0.01344966  0.00697447 -0.03185268]
  [ 0.02511679 -0.0307052  -0.0299564  -0.00356777 -0.01487728
    0.01330688 -0.04286063 -0.02206085 -0.04990126  0.03270954]
  [-0.0389869   0.02664912  0.02485662  0.00022161  0.02880296
   -0.01857207 -0.01508899 -0.03265595  0.045382

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 7111, 4645, 1327, 8399], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175  0.03367909
   0.01944667  0.01066551  0.04450018  0.00096234]
 [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175  0.03367909
   0.01944667  0.01066551  0.04450018  0.00096234]
 [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175  0.03367909
   0.01944667  0.01066551  0.04450018  0.00096234]
 [-0.01688335  0.04827087 -0.0079172  -0.02826256  0.01852175  0.03367909
   0.01944667  0.01066551  0.04450018  0.00096234]
 [-0.01431137  0.01765312  0.02915944 -0.0352341   0.01711595 -0.02865772
   0.03914508 -0.04042567 -0.02964351  0.01348101]
 [ 0.01483481 -0.02012639 -0.02603496  0.00021013  0.04989537 -0.00745595
  -0.04137442 -0.01344966  0.00697447 -0.03185268]
 [ 0.02511679 -0.0307052  -0.0299564  -0.00356777 -0.01487728  0.01330688
  -0.04286063 -0.02206085 -0.04990126  0.03270954]
 [-0.0389869   0.02664912  0.02485662  0.00022161  0.02880296 -0.01857207
  -0.01508899 -0.03265595  0.04538295 -0.02632716]]